/**
 * Lenny Space — Seed Data
 *
 * 初始节点来自 Lenny's Newsletter & Podcast 的真实公开内容。
 * 如果用户第一次进入 Lenny Space 且 lenny-nodes.json 为空，使用这些种子数据。
 *
 * 节点均为真实 episode / article，不是人造话题标签。
 * conversationId = 'lenny-seed-<slug>' 作为种子标记，不关联任何对话。
 *
 * 每个用户的 Lenny Space 数据独立存储在各自的 lenny-nodes.json 中。
 *
 * v2: 从 15 个扩充到 46 个节点（基于 ChatPRD/lennys-podcast-transcripts 真实元数据）
 */

import type { Node, Edge } from './types'

// 画布中心坐标
const CX = 1920
const CY = 1200

// 围绕中心散布的坐标生成（极坐标转直角）
function pos(angle: number, radius: number): { x: number; y: number } {
  return {
    x: Math.round(CX + Math.cos((angle * Math.PI) / 180) * radius),
    y: Math.round(CY + Math.sin((angle * Math.PI) / 180) * radius),
  }
}

export const LENNY_SEED_NODES: Node[] = [
  // ── 核心中央节点 ─────────────────────────────────────────────────────────────
  {
    id: 'lenny-seed-pmf-sean-ellis',
    title: "The Sean Ellis PMF Test",
    keywords: ['PMF', '40%', 'very disappointed'],
    date: '2024-09-05',
    conversationId: 'lenny-seed-pmf-sean-ellis',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(0, 0),   // 中央
  },

  // ── 第一圈（半径 650）─────────────────────────────────────────────────────────
  {
    id: 'lenny-seed-chesky-playbook',
    title: "Brian Chesky's New Playbook",
    keywords: ['leadership', 'details', 'culture'],
    date: '2023-11-12',
    conversationId: 'lenny-seed-chesky-playbook',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(30, 650),
  },
  {
    id: 'lenny-seed-shreyas-pm-art',
    title: "The Art of Product Management",
    keywords: ['PM', 'prioritization', 'pre-mortem'],
    date: '2022-08-25',
    conversationId: 'lenny-seed-shreyas-pm-art',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(90, 650),
  },
  {
    id: 'lenny-seed-julie-zhuo-ai-mgmt',
    title: "From Managing People to Managing AI",
    keywords: ['AI', 'leadership', 'management'],
    date: '2025-09-21',
    conversationId: 'lenny-seed-julie-zhuo-ai-mgmt',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(150, 650),
  },
  {
    id: 'lenny-seed-elena-verna-plg',
    title: "10 Growth Tactics That Never Work",
    keywords: ['PLG', 'growth tactics', 'acquisition'],
    date: '2025-01-19',
    conversationId: 'lenny-seed-elena-verna-plg',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(210, 650),
  },
  {
    id: 'lenny-seed-april-dunford-positioning',
    title: "A Step-by-Step Sales Pitch Guide",
    keywords: ['positioning', 'sales pitch', 'differentiation'],
    date: '2023-10-22',
    conversationId: 'lenny-seed-april-dunford-positioning',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(270, 650),
  },
  {
    id: 'lenny-seed-casey-winters-growth',
    title: "Why Most PMs Are Unprepared for Startups",
    keywords: ['growth', 'PM skills', 'startup'],
    date: '2023-04-14',
    conversationId: 'lenny-seed-casey-winters-growth',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(330, 650),
  },

  // ── 第二圈（半径 1200）─────────────────────────────────────────────────────────
  {
    id: 'lenny-seed-shreyas-influence',
    title: "How Great PMs Drive Influence",
    keywords: ['influence', 'stakeholders', 'alignment'],
    date: '2023-02-06',
    conversationId: 'lenny-seed-shreyas-influence',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(20, 1200),
  },
  {
    id: 'lenny-seed-marty-cagan-empowered',
    title: "Product Management Theater",
    keywords: ['outcomes', 'empowerment', 'product theater'],
    date: '2024-03-10',
    conversationId: 'lenny-seed-marty-cagan-empowered',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(60, 1200),
  },
  {
    id: 'lenny-seed-nikita-bier-virality',
    title: "How Nikita Bier Builds Viral Apps",
    keywords: ['virality', 'consumer apps', 'distribution'],
    date: '2023-07-31',
    conversationId: 'lenny-seed-nikita-bier-virality',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(100, 1200),
  },
  {
    id: 'lenny-seed-madhavan-pricing',
    title: "Pricing Your AI Product",
    keywords: ['pricing', 'AI monetization', 'value-based'],
    date: '2025-07-27',
    conversationId: 'lenny-seed-madhavan-pricing',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(140, 1200),
  },
  {
    id: 'lenny-seed-kim-scott-radical',
    title: "Radical Candor in Management",
    keywords: ['feedback', 'candor', 'team culture'],
    date: '2022-08-29',
    conversationId: 'lenny-seed-kim-scott-radical',
    category: '关系情感',
    color: '#EC4899',
    nodeType: 'memory',
    ...pos(180, 1200),
  },
  {
    id: 'lenny-seed-drew-houston-founder',
    title: "Behind the Founder: Drew Houston (Dropbox)",
    keywords: ['founder', 'vision', 'persistence'],
    date: '2025-01-09',
    conversationId: 'lenny-seed-drew-houston-founder',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(220, 1200),
  },
  {
    id: 'lenny-seed-sahil-mansuri-b2b-sales',
    title: "The Art of B2B Sales",
    keywords: ['sales', 'B2B', 'discovery calls'],
    date: '2023-03-13',
    conversationId: 'lenny-seed-sahil-mansuri-b2b-sales',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(260, 1200),
  },
  {
    id: 'lenny-seed-gokul-metrics',
    title: "Choosing the Right North Star Metric",
    keywords: ['metrics', 'north star', 'measurement'],
    date: '2022-01-01',
    conversationId: 'lenny-seed-gokul-metrics',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(300, 1200),
  },

  // ── 第三圈（半径 1900）── 新增节点 ────────────────────────────────────────────
  {
    id: 'lenny-seed-teresa-torres',
    title: "Continuous Product Discovery",
    keywords: ['discovery', 'user research', 'opportunity tree'],
    date: '2022-10-06',
    conversationId: 'lenny-seed-teresa-torres',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(0, 1900),
  },
  {
    id: 'lenny-seed-dylan-field',
    title: "Why AI Makes Design Quality a Moat",
    keywords: ['design', 'AI moat', 'craft'],
    date: '2025-10-16',
    conversationId: 'lenny-seed-dylan-field',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(18, 1900),
  },
  {
    id: 'lenny-seed-rahul-vohra',
    title: "Superhuman's Secret to Success",
    keywords: ['PMF', 'Superhuman', 'email'],
    date: '2025-03-23',
    conversationId: 'lenny-seed-rahul-vohra',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(36, 1900),
  },
  {
    id: 'lenny-seed-ben-horowitz',
    title: "$46B of Hard Truths: Why Founders Fail",
    keywords: ['founders', 'fear', 'hard decisions'],
    date: '2025-09-11',
    conversationId: 'lenny-seed-ben-horowitz',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(54, 1900),
  },
  {
    id: 'lenny-seed-tobi-lutke',
    title: "Tobi Lütke's Leadership Playbook",
    keywords: ['leadership', 'first principles', 'infinite game'],
    date: '2025-02-02',
    conversationId: 'lenny-seed-tobi-lutke',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(72, 1900),
  },
  {
    id: 'lenny-seed-melanie-perkins',
    title: "She Turned 100+ Rejections into a $42B Company",
    keywords: ['rejection', 'persistence', 'Canva'],
    date: '2025-11-02',
    conversationId: 'lenny-seed-melanie-perkins',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(90, 1900),
  },
  {
    id: 'lenny-seed-hamilton-helmer',
    title: "Business Strategy: 7 Powers",
    keywords: ['strategy', '7 powers', 'moat'],
    date: '2024-05-05',
    conversationId: 'lenny-seed-hamilton-helmer',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(108, 1900),
  },
  {
    id: 'lenny-seed-nir-eyal',
    title: "Strategies for Becoming Less Distractible",
    keywords: ['habits', 'focus', 'indistractable'],
    date: '2023-12-29',
    conversationId: 'lenny-seed-nir-eyal',
    category: '身心健康',
    color: '#10B981',
    nodeType: 'memory',
    ...pos(126, 1900),
  },
  {
    id: 'lenny-seed-seth-godin',
    title: "Building Remarkable Products and Brands",
    keywords: ['marketing', 'remarkable', 'purple cow'],
    date: '2024-12-08',
    conversationId: 'lenny-seed-seth-godin',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(144, 1900),
  },
  {
    id: 'lenny-seed-annie-duke',
    title: "How to Become a Better Decision Maker",
    keywords: ['decision making', 'poker', 'uncertainty'],
    date: '2024-05-02',
    conversationId: 'lenny-seed-annie-duke',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(162, 1900),
  },
  {
    id: 'lenny-seed-stewart-butterfield',
    title: "Mental Models for Building Products People Love",
    keywords: ['mental models', 'Slack', 'product love'],
    date: '2025-11-20',
    conversationId: 'lenny-seed-stewart-butterfield',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(180, 1900),
  },
  {
    id: 'lenny-seed-kevin-weil',
    title: "OpenAI's CPO on AI Skills and Moats",
    keywords: ['AI', 'OpenAI', 'product skills'],
    date: '2025-04-10',
    conversationId: 'lenny-seed-kevin-weil',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(198, 1900),
  },
  {
    id: 'lenny-seed-amjad-masad',
    title: "Behind the Product: Replit",
    keywords: ['Replit', 'coding', 'AI tools'],
    date: '2024-11-21',
    conversationId: 'lenny-seed-amjad-masad',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(216, 1900),
  },
  {
    id: 'lenny-seed-paul-adams',
    title: "What AI Means for Your Product Strategy",
    keywords: ['AI strategy', 'product', 'Intercom'],
    date: '2023-10-26',
    conversationId: 'lenny-seed-paul-adams',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(234, 1900),
  },
  {
    id: 'lenny-seed-claire-vo',
    title: "Bending the Universe in Your Favor",
    keywords: ['feature flags', 'experimentation', 'CPO'],
    date: '2024-04-07',
    conversationId: 'lenny-seed-claire-vo',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(252, 1900),
  },
  {
    id: 'lenny-seed-jeff-weinstein',
    title: "Building Product at Stripe: Craft and Metrics",
    keywords: ['Stripe', 'craft', 'customer obsession'],
    date: '2024-07-11',
    conversationId: 'lenny-seed-jeff-weinstein',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(270, 1900),
  },
  {
    id: 'lenny-seed-shishir-mehrotra',
    title: "The Rituals of Great Teams",
    keywords: ['team rituals', 'YouTube', 'Coda'],
    date: '2022-08-14',
    conversationId: 'lenny-seed-shishir-mehrotra',
    category: '关系情感',
    color: '#EC4899',
    nodeType: 'memory',
    ...pos(288, 1900),
  },
  {
    id: 'lenny-seed-matt-mochary',
    title: "Are Your Fears Giving You Terrible Advice?",
    keywords: ['fear', 'CEO coaching', 'emotions'],
    date: '2023-01-17',
    conversationId: 'lenny-seed-matt-mochary',
    category: '身心健康',
    color: '#10B981',
    nodeType: 'memory',
    ...pos(306, 1900),
  },
  {
    id: 'lenny-seed-gustaf-alstromer',
    title: "Lessons from 600+ YC Startups",
    keywords: ['YC', 'startups', 'Airbnb growth'],
    date: '2023-03-02',
    conversationId: 'lenny-seed-gustaf-alstromer',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(324, 1900),
  },
  {
    id: 'lenny-seed-andy-johns',
    title: "When Enough Is Enough",
    keywords: ['burnout', 'success', 'enough'],
    date: '2023-09-10',
    conversationId: 'lenny-seed-andy-johns',
    category: '身心健康',
    color: '#10B981',
    nodeType: 'memory',
    ...pos(342, 1900),
  },
  {
    id: 'lenny-seed-luc-levesque',
    title: "Leveraging Growth Advisors & Mastering SEO",
    keywords: ['SEO', 'growth advisors', 'Shopify'],
    date: '2023-06-15',
    conversationId: 'lenny-seed-luc-levesque',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(355, 1900),
  },
  {
    id: 'lenny-seed-gustaf-alstromer2',
    title: "Gustaf Alstromer: Growth from Airbnb to YC",
    keywords: ['growth', 'retention', 'metrics'],
    date: '2023-03-02',
    conversationId: 'lenny-seed-gustaf-alstromer2',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(11, 1900),
  },
]

export const LENNY_SEED_EDGES: Edge[] = [
  // ── 核心 PMF 连接 ──────────────────────────────────────────────────────────
  {
    id: 'lenny-edge-1',
    source: 'lenny-seed-pmf-sean-ellis',
    target: 'lenny-seed-chesky-playbook',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.8,
  },
  {
    id: 'lenny-edge-2',
    source: 'lenny-seed-pmf-sean-ellis',
    target: 'lenny-seed-casey-winters-growth',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.85,
  },
  {
    id: 'lenny-edge-3',
    source: 'lenny-seed-pmf-sean-ellis',
    target: 'lenny-seed-elena-verna-plg',
    edgeType: 'logical',
    relation: '依赖于',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.82,
  },
  {
    id: 'lenny-edge-4',
    source: 'lenny-seed-shreyas-pm-art',
    target: 'lenny-seed-shreyas-influence',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.9,
  },
  {
    id: 'lenny-edge-5',
    source: 'lenny-seed-chesky-playbook',
    target: 'lenny-seed-marty-cagan-empowered',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.78,
  },
  {
    id: 'lenny-edge-6',
    source: 'lenny-seed-april-dunford-positioning',
    target: 'lenny-seed-madhavan-pricing',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.83,
  },
  {
    id: 'lenny-edge-7',
    source: 'lenny-seed-casey-winters-growth',
    target: 'lenny-seed-nikita-bier-virality',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.77,
  },
  {
    id: 'lenny-edge-8',
    source: 'lenny-seed-chesky-playbook',
    target: 'lenny-seed-kim-scott-radical',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.75,
  },
  {
    id: 'lenny-edge-9',
    source: 'lenny-seed-casey-winters-growth',
    target: 'lenny-seed-gokul-metrics',
    edgeType: 'logical',
    relation: '依赖于',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.8,
  },
  {
    id: 'lenny-edge-10',
    source: 'lenny-seed-drew-houston-founder',
    target: 'lenny-seed-pmf-sean-ellis',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.76,
  },
  // ── 新增边（第三圈连接）──────────────────────────────────────────────────────
  {
    id: 'lenny-edge-11',
    source: 'lenny-seed-pmf-sean-ellis',
    target: 'lenny-seed-rahul-vohra',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.88,
  },
  {
    id: 'lenny-edge-12',
    source: 'lenny-seed-marty-cagan-empowered',
    target: 'lenny-seed-teresa-torres',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.84,
  },
  {
    id: 'lenny-edge-13',
    source: 'lenny-seed-madhavan-pricing',
    target: 'lenny-seed-april-dunford-positioning',
    edgeType: 'logical',
    relation: '依赖于',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.79,
  },
  {
    id: 'lenny-edge-14',
    source: 'lenny-seed-chesky-playbook',
    target: 'lenny-seed-ben-horowitz',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.75,
  },
  {
    id: 'lenny-edge-15',
    source: 'lenny-seed-chesky-playbook',
    target: 'lenny-seed-tobi-lutke',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.76,
  },
  {
    id: 'lenny-edge-16',
    source: 'lenny-seed-hamilton-helmer',
    target: 'lenny-seed-april-dunford-positioning',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.81,
  },
  {
    id: 'lenny-edge-17',
    source: 'lenny-seed-casey-winters-growth',
    target: 'lenny-seed-gustaf-alstromer',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.78,
  },
  {
    id: 'lenny-edge-18',
    source: 'lenny-seed-gokul-metrics',
    target: 'lenny-seed-jeff-weinstein',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.77,
  },
  {
    id: 'lenny-edge-19',
    source: 'lenny-seed-julie-zhuo-ai-mgmt',
    target: 'lenny-seed-kevin-weil',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.82,
  },
  {
    id: 'lenny-edge-20',
    source: 'lenny-seed-elena-verna-plg',
    target: 'lenny-seed-luc-levesque',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.79,
  },
]

/**
 * 从 GitHub 拉取 Lenny 播客 transcript 列表
 * 返回已知的 episode slug 列表（用于生成或扩展节点）
 */
export const LENNY_TRANSCRIPT_BASE_URL =
  'https://raw.githubusercontent.com/ChatPRD/lennys-podcast-transcripts/main/episodes'

/**
 * 已知的高质量 episode slugs（优先加载）
 */
export const LENNY_FEATURED_SLUGS = [
  'brian-chesky',
  'shreyas-doshi',
  'julie-zhuo',
  'sean-ellis',
  'elena-verna',
  'april-dunford',
  'casey-winters',
  'marty-cagan',
  'nikita-bier',
  'drew-houston',
  'kim-scott',
  'gokul-rajaram',
  'madhavan-ramanujam',
  'sahil-mansuri',
  'lulu-cheng-meservey',
  'stewart-butterfield',
  'tobi-lutke',
  'dylan-field',
  'kunal-shah',
  'ryan-hoover',
  'teresa-torres',
  'rahul-vohra',
  'ben-horowitz',
  'melanie-perkins',
  'hamilton-helmer',
  'nir-eyal',
  'seth-godin',
  'annie-duke',
  'kevin-weil',
  'amjad-masad',
  'paul-adams',
  'claire-vo',
  'jeff-weinstein',
  'shishir-mehrotra',
  'matt-mochary',
  'gustaf-alstromer',
  'andy-johns',
  'luc-levesque',
]
