/**
 * Paul Graham Space — Seed Data
 *
 * 内容来源：anima-base / people/startup/paul-graham/
 * https://github.com/fisher-byte/anima-base
 *
 * 节点基于 Paul Graham 在 paulgraham.com 发表的核心文章，
 * 涵盖创业哲学、思维方法、财富创造、人生选择等主题。
 *
 * conversationId = 'pg-seed-<slug>' 作为种子标记，不关联任何对话。
 */

import type { Node, Edge } from './types'

// 画布中心坐标
const CX = 1920
const CY = 1200

function pos(angle: number, radius: number): { x: number; y: number } {
  return {
    x: Math.round(CX + Math.cos((angle * Math.PI) / 180) * radius),
    y: Math.round(CY + Math.sin((angle * Math.PI) / 180) * radius),
  }
}

export const PG_SEED_NODES: Node[] = [
  // ── 核心中央节点 ─────────────────────────────────────────────────────────────
  {
    id: 'pg-seed-startup-equals-growth',
    title: 'Startup = Growth',
    keywords: ['startup', 'growth', 'definition', '10% weekly'],
    date: '2012-09-01',
    conversationId: 'pg-seed-startup-equals-growth',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(0, 0),
  },

  // ── 第一圈（半径 650）─────────────────────────────────────────────────────────
  {
    id: 'pg-seed-do-things-that-dont-scale',
    title: "Do Things That Don't Scale",
    keywords: ['unscalable', 'recruiting', 'delight users', 'manual'],
    date: '2013-07-01',
    conversationId: 'pg-seed-do-things-that-dont-scale',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(0, 650),
  },
  {
    id: 'pg-seed-how-to-get-startup-ideas',
    title: 'How to Get Startup Ideas',
    keywords: ['ideas', 'problems', 'live in future', 'schlep filter'],
    date: '2012-11-01',
    conversationId: 'pg-seed-how-to-get-startup-ideas',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(60, 650),
  },
  {
    id: 'pg-seed-how-to-start-a-startup',
    title: 'How to Start a Startup',
    keywords: ['good people', 'users want', 'spend little', 'three elements'],
    date: '2005-03-01',
    conversationId: 'pg-seed-how-to-start-a-startup',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(120, 650),
  },
  {
    id: 'pg-seed-founder-mode',
    title: 'Founder Mode',
    keywords: ['founder mode', 'manager mode', 'Brian Chesky', 'Steve Jobs', 'skip-level'],
    date: '2024-09-01',
    conversationId: 'pg-seed-founder-mode',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(180, 650),
  },
  {
    id: 'pg-seed-how-to-do-great-work',
    title: 'How to Do Great Work',
    keywords: ['great work', 'curiosity', 'ambition', 'originality', 'daily habits'],
    date: '2023-07-01',
    conversationId: 'pg-seed-how-to-do-great-work',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(240, 650),
  },
  {
    id: 'pg-seed-how-to-make-wealth',
    title: 'How to Make Wealth',
    keywords: ['wealth', 'not money', 'measurability', 'leverage', 'technology'],
    date: '2004-05-01',
    conversationId: 'pg-seed-how-to-make-wealth',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(300, 650),
  },

  // ── 第二圈（半径 1200）─────────────────────────────────────────────────────────
  {
    id: 'pg-seed-how-to-think-for-yourself',
    title: 'How to Think for Yourself',
    keywords: ['independent-minded', 'conventional', 'contrarian', 'truth over acceptance'],
    date: '2020-11-01',
    conversationId: 'pg-seed-how-to-think-for-yourself',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(0, 1200),
  },
  {
    id: 'pg-seed-how-to-disagree',
    title: 'How to Disagree',
    keywords: ['DH0-DH6', 'disagreement pyramid', 'ad hominem', 'central point'],
    date: '2008-03-01',
    conversationId: 'pg-seed-how-to-disagree',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(40, 1200),
  },
  {
    id: 'pg-seed-what-to-do',
    title: 'What to Do',
    keywords: ['help people', 'make good things', 'originality', 'potential'],
    date: '2025-03-01',
    conversationId: 'pg-seed-what-to-do',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(80, 1200),
  },
  {
    id: 'pg-seed-top-idea-in-your-mind',
    title: 'The Top Idea in Your Mind',
    keywords: ['top idea', 'background thinking', 'shower thoughts', 'money problems'],
    date: '2010-07-01',
    conversationId: 'pg-seed-top-idea-in-your-mind',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(120, 1200),
  },
  {
    id: 'pg-seed-do-what-you-love',
    title: 'How to Do What You Love',
    keywords: ['prestige trap', 'genuine interest', 'passion', 'excellence'],
    date: '2006-01-01',
    conversationId: 'pg-seed-do-what-you-love',
    category: '身心健康',
    color: '#10B981',
    nodeType: 'memory',
    ...pos(160, 1200),
  },
  {
    id: 'pg-seed-top-of-todo-list',
    title: "Don't Ignore Your Dreams",
    keywords: ['regrets', 'omission errors', 'dreams', 'friendships', 'be happy'],
    date: '2012-04-01',
    conversationId: 'pg-seed-top-of-todo-list',
    category: '身心健康',
    color: '#10B981',
    nodeType: 'memory',
    ...pos(200, 1200),
  },
  {
    id: 'pg-seed-beating-the-averages',
    title: 'Beating the Averages',
    keywords: ['Lisp', 'Blub paradox', 'technology edge', 'Viaweb'],
    date: '2001-04-01',
    conversationId: 'pg-seed-beating-the-averages',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(240, 1200),
  },
  {
    id: 'pg-seed-be-good',
    title: 'Be Good',
    keywords: ['be good', 'business model', 'trust', 'users first'],
    date: '2008-04-01',
    conversationId: 'pg-seed-be-good',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(280, 1200),
  },
  {
    id: 'pg-seed-mean-people-fail',
    title: 'Mean People Fail',
    keywords: ['meanness', 'failure', 'talent', 'non-zero sum', 'transcend'],
    date: '2014-11-01',
    conversationId: 'pg-seed-mean-people-fail',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(320, 1200),
  },

  // ── 第三圈（半径 1850）─────────────────────────────────────────────────────────
  {
    id: 'pg-seed-18-mistakes',
    title: 'The 18 Mistakes That Kill Startups',
    keywords: ['single founder', 'bad location', 'stubbornness', 'mistakes'],
    date: '2006-10-01',
    conversationId: 'pg-seed-18-mistakes',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(0, 1850),
  },
  {
    id: 'pg-seed-ideas-execution',
    title: 'Ideas vs Execution',
    keywords: ['execution', 'iteration', 'MVP', 'launch fast'],
    date: '2005-03-01',
    conversationId: 'pg-seed-ideas-execution',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(24, 1850),
  },
  {
    id: 'pg-seed-yc-model',
    title: 'The YC Model',
    keywords: ['YC', 'accelerator', 'seed funding', 'batch model'],
    date: '2005-01-01',
    conversationId: 'pg-seed-yc-model',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(48, 1850),
  },
  {
    id: 'pg-seed-well-theory',
    title: 'The Well Theory of Early Users',
    keywords: ['well theory', 'narrow deep', 'early adopters', 'intense need'],
    date: '2012-11-01',
    conversationId: 'pg-seed-well-theory',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(72, 1850),
  },
  {
    id: 'pg-seed-curiosity-as-compass',
    title: 'Curiosity as Your Best Guide',
    keywords: ['curiosity', 'compass', 'never lies', 'follow interest'],
    date: '2023-07-01',
    conversationId: 'pg-seed-curiosity-as-compass',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(96, 1850),
  },
  {
    id: 'pg-seed-schlep-blindness',
    title: 'Schlep Blindness',
    keywords: ['schlep filter', 'unsexy filter', 'hidden opportunities', 'messy problems'],
    date: '2012-01-01',
    conversationId: 'pg-seed-schlep-blindness',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(120, 1850),
  },
  {
    id: 'pg-seed-good-and-bad-procrastination',
    title: 'Good and Bad Procrastination',
    keywords: ['procrastination', 'important vs urgent', 'distraction', 'big things'],
    date: '2005-12-01',
    conversationId: 'pg-seed-good-and-bad-procrastination',
    category: '身心健康',
    color: '#10B981',
    nodeType: 'memory',
    ...pos(144, 1850),
  },
  {
    id: 'pg-seed-prestige-trap',
    title: 'The Prestige Trap',
    keywords: ['prestige', 'status', 'warps beliefs', 'avoid'],
    date: '2006-01-01',
    conversationId: 'pg-seed-prestige-trap',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(168, 1850),
  },
  {
    id: 'pg-seed-wealth-not-zero-sum',
    title: 'Wealth Is Not Zero-Sum',
    keywords: ['wealth creation', 'pie', 'technology', 'non-zero sum'],
    date: '2004-05-01',
    conversationId: 'pg-seed-wealth-not-zero-sum',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(192, 1850),
  },
  {
    id: 'pg-seed-independent-mind-types',
    title: 'Two Types of Minds',
    keywords: ['independent', 'conventional', 'scientists', 'investors', 'entrepreneurs'],
    date: '2020-11-01',
    conversationId: 'pg-seed-independent-mind-types',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(216, 1850),
  },
  {
    id: 'pg-seed-growth-benchmarks',
    title: 'Growth Benchmarks: 1% 5% 10%',
    keywords: ['1% weekly', '5% weekly', '10% weekly', 'compound', '142x'],
    date: '2012-09-01',
    conversationId: 'pg-seed-growth-benchmarks',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(240, 1850),
  },
  {
    id: 'pg-seed-live-in-future',
    title: 'Live in the Future, Build What\'s Missing',
    keywords: ['live in future', 'organic ideas', 'noticing gaps', 'leading edge'],
    date: '2012-11-01',
    conversationId: 'pg-seed-live-in-future',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(264, 1850),
  },
  {
    id: 'pg-seed-contrarian-insight',
    title: 'The Contrarian Insight',
    keywords: ['contrarian', 'bad idea that is good', 'consensus wrong', 'secret'],
    date: '2020-11-01',
    conversationId: 'pg-seed-contrarian-insight',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(288, 1850),
  },
  {
    id: 'pg-seed-disagree-levels',
    title: 'DH0–DH6: The Disagreement Hierarchy',
    keywords: ['DH0 insults', 'DH6 central point', 'internet discourse', 'hierarchy'],
    date: '2008-03-01',
    conversationId: 'pg-seed-disagree-levels',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(312, 1850),
  },
  {
    id: 'pg-seed-makers-schedule',
    title: "Maker's Schedule vs Manager's Schedule",
    keywords: ["maker's schedule", "manager's schedule", 'meetings', 'flow state'],
    date: '2009-07-01',
    conversationId: 'pg-seed-makers-schedule',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(336, 1850),
  },
  {
    id: 'pg-seed-keep-your-identity-small',
    title: 'Keep Your Identity Small',
    keywords: ['identity', 'belief', 'religion politics', 'open mind'],
    date: '2009-02-01',
    conversationId: 'pg-seed-keep-your-identity-small',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(355, 1850),
  },
]

export const PG_SEED_EDGES: Edge[] = [
  // 核心连接：startup = growth 作为枢纽
  {
    id: 'pg-edge-1',
    source: 'pg-seed-startup-equals-growth',
    target: 'pg-seed-do-things-that-dont-scale',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.88,
  },
  {
    id: 'pg-edge-2',
    source: 'pg-seed-startup-equals-growth',
    target: 'pg-seed-how-to-get-startup-ideas',
    edgeType: 'logical',
    relation: '依赖于',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.85,
  },
  {
    id: 'pg-edge-3',
    source: 'pg-seed-startup-equals-growth',
    target: 'pg-seed-growth-benchmarks',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.95,
  },
  {
    id: 'pg-edge-4',
    source: 'pg-seed-how-to-start-a-startup',
    target: 'pg-seed-18-mistakes',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.9,
  },
  {
    id: 'pg-edge-5',
    source: 'pg-seed-how-to-get-startup-ideas',
    target: 'pg-seed-well-theory',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.87,
  },
  {
    id: 'pg-edge-6',
    source: 'pg-seed-how-to-get-startup-ideas',
    target: 'pg-seed-live-in-future',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.92,
  },
  {
    id: 'pg-edge-7',
    source: 'pg-seed-how-to-get-startup-ideas',
    target: 'pg-seed-schlep-blindness',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.88,
  },
  {
    id: 'pg-edge-8',
    source: 'pg-seed-how-to-do-great-work',
    target: 'pg-seed-curiosity-as-compass',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.93,
  },
  {
    id: 'pg-edge-9',
    source: 'pg-seed-how-to-do-great-work',
    target: 'pg-seed-do-what-you-love',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.86,
  },
  {
    id: 'pg-edge-10',
    source: 'pg-seed-how-to-think-for-yourself',
    target: 'pg-seed-contrarian-insight',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.89,
  },
  {
    id: 'pg-edge-11',
    source: 'pg-seed-how-to-think-for-yourself',
    target: 'pg-seed-independent-mind-types',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.94,
  },
  {
    id: 'pg-edge-12',
    source: 'pg-seed-how-to-disagree',
    target: 'pg-seed-disagree-levels',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.97,
  },
  {
    id: 'pg-edge-13',
    source: 'pg-seed-founder-mode',
    target: 'pg-seed-how-to-start-a-startup',
    edgeType: 'logical',
    relation: '重新思考了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.82,
  },
  {
    id: 'pg-edge-14',
    source: 'pg-seed-how-to-make-wealth',
    target: 'pg-seed-wealth-not-zero-sum',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.91,
  },
  {
    id: 'pg-edge-15',
    source: 'pg-seed-do-what-you-love',
    target: 'pg-seed-prestige-trap',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.85,
  },
  {
    id: 'pg-edge-16',
    source: 'pg-seed-top-of-todo-list',
    target: 'pg-seed-good-and-bad-procrastination',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.8,
  },
  {
    id: 'pg-edge-17',
    source: 'pg-seed-be-good',
    target: 'pg-seed-mean-people-fail',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.83,
  },
  {
    id: 'pg-edge-18',
    source: 'pg-seed-top-idea-in-your-mind',
    target: 'pg-seed-makers-schedule',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.79,
  },
  {
    id: 'pg-edge-19',
    source: 'pg-seed-keep-your-identity-small',
    target: 'pg-seed-how-to-think-for-yourself',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.86,
  },
  {
    id: 'pg-edge-20',
    source: 'pg-seed-what-to-do',
    target: 'pg-seed-how-to-do-great-work',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.88,
  },
]
