/**
 * Wang Huiwen Space — Seed Data
 *
 * 内容来源：anima-base / people/product/wang-huiwen/
 * https://github.com/fisher-byte/anima-base
 *
 * 节点基于王慧文在清华大学产品管理课、极客公园访谈及公开演讲中的核心观点，
 * 涵盖产品方法论、创业哲学、组织管理、AI时代创业等主题。
 *
 * conversationId = 'wang-seed-<slug>' 作为种子标记，不关联任何对话。
 */

import type { Node, Edge } from './types'

// 画布中心坐标
const CX = 1920
const CY = 1200

function pos(angle: number, radius: number): { x: number; y: number } {
  return {
    x: Math.round(CX + Math.cos((angle * Math.PI) / 180) * radius),
    y: Math.round(CY + Math.sin((angle * Math.PI) / 180) * radius),
  }
}

export const WANG_SEED_NODES: Node[] = [
  // ── 核心中央节点 ─────────────────────────────────────────────────────────────
  {
    id: 'wang-seed-core-competitiveness',
    title: '真正的核心竞争力只有两个',
    keywords: ['团队能力', '用户洞察', '核心竞争力', '创业本质'],
    date: '2019-01-01',
    conversationId: 'wang-seed-core-competitiveness',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(0, 0),   // 中央
  },

  // ── 第一圈（半径 650）── 产品方法论 ──────────────────────────────────────────
  {
    id: 'wang-seed-pi-talent',
    title: 'π型人才：一横两竖的复合能力',
    keywords: ['π型人才', '复合能力', '广度深度', '摩擦成本'],
    date: '2019-01-01',
    conversationId: 'wang-seed-pi-talent',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(0, 650),
  },
  {
    id: 'wang-seed-following-rules',
    title: '发现并坚持遵循规律',
    keywords: ['遵循规律', '真理胜利', '熟人社交', '校内网'],
    date: '2019-01-01',
    conversationId: 'wang-seed-following-rules',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(60, 650),
  },
  {
    id: 'wang-seed-latecomer-advantage',
    title: '后发优势：最终成功通常不是第一家',
    keywords: ['后发优势', 'iPhone vs Nokia', 'Chrome vs IE', '学习先行者'],
    date: '2019-01-01',
    conversationId: 'wang-seed-latecomer-advantage',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(120, 650),
  },
  {
    id: 'wang-seed-discover-opportunity',
    title: '发现机会的能力是最稀缺的能力',
    keywords: ['发现机会', '稀缺能力', '市场洞察', '创业嗅觉'],
    date: '2019-01-01',
    conversationId: 'wang-seed-discover-opportunity',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(180, 650),
  },
  {
    id: 'wang-seed-continuous-learning',
    title: '持续学习进步的能力',
    keywords: ['持续学习', '快速迭代', '知识更新', '成长型思维'],
    date: '2019-01-01',
    conversationId: 'wang-seed-continuous-learning',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(240, 650),
  },
  {
    id: 'wang-seed-dunning-kruger',
    title: '大多数人不知道自己处于无知的顶峰',
    keywords: ['邓宁-克鲁格效应', '无知顶峰', '认知偏差', '自我觉察'],
    date: '2019-01-01',
    conversationId: 'wang-seed-dunning-kruger',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(300, 650),
  },

  // ── 第二圈（半径 1200）── 清华课程七讲 ──────────────────────────────────────
  {
    id: 'wang-seed-lesson-1-intro',
    title: '清华课第一讲：三个故事与基础方法论',
    keywords: ['方法论', '校内网', 'π型人才', '核心竞争力'],
    date: '2019-01-01',
    conversationId: 'wang-seed-lesson-1-intro',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(0, 1200),
  },
  {
    id: 'wang-seed-lesson-2-success-failure',
    title: '清华课第二讲：成功与失败案例',
    keywords: ['案例分析', '成功经验', '失败教训', '模式归纳'],
    date: '2019-01-01',
    conversationId: 'wang-seed-lesson-2-success-failure',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(40, 1200),
  },
  {
    id: 'wang-seed-lesson-3-latecomer',
    title: '清华课第三讲：后发优势深度解析',
    keywords: ['后发优势', '产品经理关键', '技术不是瓶颈', 'iPhone案例'],
    date: '2019-01-01',
    conversationId: 'wang-seed-lesson-3-latecomer',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(80, 1200),
  },
  {
    id: 'wang-seed-lesson-4-product-decision',
    title: '清华课第四讲：产品决策框架',
    keywords: ['产品决策', '需求判断', '优先级', '决策方法'],
    date: '2019-01-01',
    conversationId: 'wang-seed-lesson-4-product-decision',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(120, 1200),
  },
  {
    id: 'wang-seed-lesson-5-business-model',
    title: '清华课第五讲：商业模式设计',
    keywords: ['商业模式', '盈利模式', '价值主张', '竞争护城河'],
    date: '2019-01-01',
    conversationId: 'wang-seed-lesson-5-business-model',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(160, 1200),
  },
  {
    id: 'wang-seed-lesson-6-org-building',
    title: '清华课第六讲：组织建设',
    keywords: ['组织建设', '团队搭建', '人才识别', '文化形成'],
    date: '2019-01-01',
    conversationId: 'wang-seed-lesson-6-org-building',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(200, 1200),
  },
  {
    id: 'wang-seed-lesson-7-strategy-execution',
    title: '清华课第七讲：战略与执行',
    keywords: ['战略执行', '路线规划', '资源分配', '战略定力'],
    date: '2019-01-01',
    conversationId: 'wang-seed-lesson-7-strategy-execution',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(240, 1200),
  },
  {
    id: 'wang-seed-meituan-growth',
    title: '美团增长模式：团队能力驱动',
    keywords: ['美团增长', '团队驱动', '地推文化', '本地生活'],
    date: '2020-01-01',
    conversationId: 'wang-seed-meituan-growth',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(280, 1200),
  },
  {
    id: 'wang-seed-ai-era-entrepreneurship',
    title: 'AI时代：谁做成了我都为他鼓掌',
    keywords: ['AGI创业', 'AI时代', '大格局', '开放心态'],
    date: '2023-01-01',
    conversationId: 'wang-seed-ai-era-entrepreneurship',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(320, 1200),
  },

  // ── 第三圈（半径 1850）── 延伸洞见 ──────────────────────────────────────────
  {
    id: 'wang-seed-xiaonei-familiar-social',
    title: '校内网：坚持熟人社交，大众最终被真理扭转',
    keywords: ['校内网', '熟人社交', '坚守规律', '真理胜利'],
    date: '2019-01-01',
    conversationId: 'wang-seed-xiaonei-familiar-social',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(0, 1850),
  },
  {
    id: 'wang-seed-engineer-to-pm',
    title: '工程师转产品：2/3失败，但成功者成就更高',
    keywords: ['工程师转型', '产品经理', '转型风险', '成就上限'],
    date: '2019-01-01',
    conversationId: 'wang-seed-engineer-to-pm',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(24, 1850),
  },
  {
    id: 'wang-seed-involution-trap',
    title: '内卷：资源有限时竞争激烈化',
    keywords: ['内卷', '竞争烈度', '资源分配', '破局思路'],
    date: '2019-01-01',
    conversationId: 'wang-seed-involution-trap',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(48, 1850),
  },
  {
    id: 'wang-seed-values-thinking-mode',
    title: '产品经理的核心：价值观与思维方式',
    keywords: ['价值观', '思维方式', '产品经理素养', '专业背景无关'],
    date: '2019-01-01',
    conversationId: 'wang-seed-values-thinking-mode',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(72, 1850),
  },
  {
    id: 'wang-seed-2025-ai-rise',
    title: '2025年：AI时代的创业机遇',
    keywords: ['AI机遇', '大模型', '创业方向', '技术驱动'],
    date: '2025-01-01',
    conversationId: 'wang-seed-2025-ai-rise',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(96, 1850),
  },
  {
    id: 'wang-seed-internet-ab-sides',
    title: '互联网的AB面：阳光与阴暗',
    keywords: ['互联网双面', '科技伦理', '平台责任', '社会影响'],
    date: '2017-01-01',
    conversationId: 'wang-seed-internet-ab-sides',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(120, 1850),
  },
  {
    id: 'wang-seed-how-to-make-decisions',
    title: '如何做决策：不确定性下的理性选择',
    keywords: ['决策框架', '不确定性', '理性决策', '信息不对称'],
    date: '2021-01-01',
    conversationId: 'wang-seed-how-to-make-decisions',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(144, 1850),
  },
  {
    id: 'wang-seed-geekpark-core-comp',
    title: '极客公园：核心竞争力的本质',
    keywords: ['核心竞争力', '团队能力', '用户洞察', '极客公园'],
    date: '2019-01-01',
    conversationId: 'wang-seed-geekpark-core-comp',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(168, 1850),
  },
  {
    id: 'wang-seed-luck-in-startup',
    title: '创业中的运气：如何正确看待偶然性',
    keywords: ['运气', '偶然性', '创业心态', '概率思维'],
    date: '2019-01-01',
    conversationId: 'wang-seed-luck-in-startup',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(192, 1850),
  },
  {
    id: 'wang-seed-category-classification',
    title: '行业分类思维：理解不同赛道的规律',
    keywords: ['行业分类', '赛道规律', '竞争格局', '市场结构'],
    date: '2019-01-01',
    conversationId: 'wang-seed-category-classification',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(216, 1850),
  },
  {
    id: 'wang-seed-entrepreneurial-journey-2025',
    title: '2025年创业之路：AI创业者的心路',
    keywords: ['AI创业', '创业历程', '坚持与放弃', '大模型应用'],
    date: '2025-01-01',
    conversationId: 'wang-seed-entrepreneurial-journey-2025',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(240, 1850),
  },
  {
    id: 'wang-seed-36kr-agi-journey',
    title: '36Kr专访：AGI之路，谁成功我都鼓掌',
    keywords: ['AGI', '36Kr专访', 'AI追求', '开放竞争'],
    date: '2023-01-01',
    conversationId: 'wang-seed-36kr-agi-journey',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(264, 1850),
  },
  {
    id: 'wang-seed-pm-background-doesnt-matter',
    title: '产品经理专业背景不重要，核心是思维',
    keywords: ['专业背景', '思维方式', '产品经理准入', '多元背景'],
    date: '2019-01-01',
    conversationId: 'wang-seed-pm-background-doesnt-matter',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(288, 1850),
  },
  {
    id: 'wang-seed-tsinghua-course-2024',
    title: '2024年清华讲座：AI时代产品人的新挑战',
    keywords: ['AI时代', '产品经理新挑战', '技术赋能', '认知升级'],
    date: '2024-01-01',
    conversationId: 'wang-seed-tsinghua-course-2024',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(312, 1850),
  },
]

export const WANG_SEED_EDGES: Edge[] = [
  // 核心：真正的核心竞争力
  {
    id: 'wang-edge-1',
    source: 'wang-seed-core-competitiveness',
    target: 'wang-seed-discover-opportunity',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.95,
  },
  {
    id: 'wang-edge-2',
    source: 'wang-seed-core-competitiveness',
    target: 'wang-seed-continuous-learning',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.93,
  },
  {
    id: 'wang-edge-3',
    source: 'wang-seed-core-competitiveness',
    target: 'wang-seed-meituan-growth',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.88,
  },
  {
    id: 'wang-edge-4',
    source: 'wang-seed-pi-talent',
    target: 'wang-seed-engineer-to-pm',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.87,
  },
  {
    id: 'wang-edge-5',
    source: 'wang-seed-pi-talent',
    target: 'wang-seed-pm-background-doesnt-matter',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.84,
  },
  {
    id: 'wang-edge-6',
    source: 'wang-seed-following-rules',
    target: 'wang-seed-xiaonei-familiar-social',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.92,
  },
  {
    id: 'wang-edge-7',
    source: 'wang-seed-latecomer-advantage',
    target: 'wang-seed-lesson-3-latecomer',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.96,
  },
  {
    id: 'wang-edge-8',
    source: 'wang-seed-lesson-1-intro',
    target: 'wang-seed-pi-talent',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.9,
  },
  {
    id: 'wang-edge-9',
    source: 'wang-seed-lesson-1-intro',
    target: 'wang-seed-following-rules',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.91,
  },
  {
    id: 'wang-edge-10',
    source: 'wang-seed-lesson-5-business-model',
    target: 'wang-seed-category-classification',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.82,
  },
  {
    id: 'wang-edge-11',
    source: 'wang-seed-lesson-4-product-decision',
    target: 'wang-seed-how-to-make-decisions',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.89,
  },
  {
    id: 'wang-edge-12',
    source: 'wang-seed-lesson-7-strategy-execution',
    target: 'wang-seed-lesson-5-business-model',
    edgeType: 'logical',
    relation: '依赖于',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.8,
  },
  {
    id: 'wang-edge-13',
    source: 'wang-seed-dunning-kruger',
    target: 'wang-seed-geekpark-core-comp',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.83,
  },
  {
    id: 'wang-edge-14',
    source: 'wang-seed-ai-era-entrepreneurship',
    target: 'wang-seed-36kr-agi-journey',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.91,
  },
  {
    id: 'wang-edge-15',
    source: 'wang-seed-ai-era-entrepreneurship',
    target: 'wang-seed-2025-ai-rise',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.88,
  },
  {
    id: 'wang-edge-16',
    source: 'wang-seed-2025-ai-rise',
    target: 'wang-seed-entrepreneurial-journey-2025',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.86,
  },
  {
    id: 'wang-edge-17',
    source: 'wang-seed-internet-ab-sides',
    target: 'wang-seed-dunning-kruger',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.75,
  },
  {
    id: 'wang-edge-18',
    source: 'wang-seed-values-thinking-mode',
    target: 'wang-seed-pm-background-doesnt-matter',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.87,
  },
  {
    id: 'wang-edge-19',
    source: 'wang-seed-lesson-1-intro',
    target: 'wang-seed-luck-in-startup',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.78,
  },
  {
    id: 'wang-edge-20',
    source: 'wang-seed-tsinghua-course-2024',
    target: 'wang-seed-ai-era-entrepreneurship',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.85,
  },
]
