/**
 * Zhang Xiaolong Space — Seed Data
 *
 * 内容来源：anima-base / people/product/zhang-xiaolong/
 * https://github.com/fisher-byte/anima-base
 *
 * 节点基于张小龙在微信公开课、内部分享及媒体访谈中的核心观点，
 * 涵盖产品哲学、用户洞察、微信方法论、产品设计等主题。
 *
 * conversationId = 'zhang-seed-<slug>' 作为种子标记，不关联任何对话。
 */

import type { Node, Edge } from './types'

// 画布中心坐标
const CX = 1920
const CY = 1200

function pos(angle: number, radius: number): { x: number; y: number } {
  return {
    x: Math.round(CX + Math.cos((angle * Math.PI) / 180) * radius),
    y: Math.round(CY + Math.sin((angle * Math.PI) / 180) * radius),
  }
}

export const ZHANG_SEED_NODES: Node[] = [
  // ── 核心中央节点 ─────────────────────────────────────────────────────────────
  {
    id: 'zhang-seed-yong-wan-ji-zou',
    title: '用完即走，走了还会回来',
    keywords: ['用完即走', '克制', '工具哲学', '好产品'],
    date: '2012-01-01',
    conversationId: 'zhang-seed-yong-wan-ji-zou',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(0, 0),   // 中央
  },

  // ── 第一圈（半径 650）── 产品设计哲学 ──────────────────────────────────────
  {
    id: 'zhang-seed-77-product-principles',
    title: '77条产品原则',
    keywords: ['产品原则', '用户懒惰', '简单审美', '手机延伸'],
    date: '2012-01-01',
    conversationId: 'zhang-seed-77-product-principles',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(0, 650),
  },
  {
    id: 'zhang-seed-good-product-standards',
    title: '好产品的12个标准',
    keywords: ['本能反应', '单一路径', '默认体验', '用户思维'],
    date: '2012-01-01',
    conversationId: 'zhang-seed-good-product-standards',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(60, 650),
  },
  {
    id: 'zhang-seed-jian-dan-meigangguan',
    title: '简单是一种审美观',
    keywords: ['简单', '审美', '克制', '极简设计'],
    date: '2012-01-01',
    conversationId: 'zhang-seed-jian-dan-meigangguan',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(120, 650),
  },
  {
    id: 'zhang-seed-renxing-vs-jishu',
    title: '从需求而非技术出发',
    keywords: ['人性洞察', '需求', '工具', '产品哲学'],
    date: '2013-01-01',
    conversationId: 'zhang-seed-renxing-vs-jishu',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(180, 650),
  },
  {
    id: 'zhang-seed-shejin-yiyao',
    title: '摇一摇：单一规则的群体涌现',
    keywords: ['摇一摇', '群体涌现', '简单规则', '人机交互'],
    date: '2013-01-01',
    conversationId: 'zhang-seed-shejin-yiyao',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(240, 650),
  },
  {
    id: 'zhang-seed-peopleset-guanxi',
    title: '沟通就是强加人设的过程',
    keywords: ['人设', '社交本质', '朋友圈', '沟通哲学'],
    date: '2019-01-09',
    conversationId: 'zhang-seed-peopleset-guanxi',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(300, 650),
  },

  // ── 第二圈（半径 1200）── 微信公开课 ────────────────────────────────────────
  {
    id: 'zhang-seed-2019-weixin-open-class',
    title: '2019微信公开课：十亿用户与社交本质',
    keywords: ['十亿用户', '社交广场', '朋友圈哲学', '小程序'],
    date: '2019-01-09',
    conversationId: 'zhang-seed-2019-weixin-open-class',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(0, 1200),
  },
  {
    id: 'zhang-seed-2020-weixin-open-class',
    title: '2020微信公开课：信息互联的七个思考',
    keywords: ['隐私与广告', '信息推送', '短内容', '表达需求'],
    date: '2020-01-01',
    conversationId: 'zhang-seed-2020-weixin-open-class',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(40, 1200),
  },
  {
    id: 'zhang-seed-2021-weixin-open-class',
    title: '2021微信公开课：十年回望与视频号',
    keywords: ['微信十年', '视频号', '小而美', '数字奴隶'],
    date: '2021-01-19',
    conversationId: 'zhang-seed-2021-weixin-open-class',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(80, 1200),
  },
  {
    id: 'zhang-seed-2021-ten-years-methodology',
    title: '微信十年：三端一念产品方法论',
    keywords: ['三端一念', '顺势而为', '用户故事', '灰度测试'],
    date: '2021-01-01',
    conversationId: 'zhang-seed-2021-ten-years-methodology',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(120, 1200),
  },
  {
    id: 'zhang-seed-2018-jump-game',
    title: '2018微信公开课：跳一跳与探索线下世界',
    keywords: ['跳一跳', '好产品无需发布会', '线下连接', '信任与公平'],
    date: '2018-01-15',
    conversationId: 'zhang-seed-2018-jump-game',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(160, 1200),
  },
  {
    id: 'zhang-seed-xiaochengxu-dazhi',
    title: '小程序：让创造者体现价值',
    keywords: ['小程序', '去中心化', '创造者价值', '搜索直达'],
    date: '2019-01-09',
    conversationId: 'zhang-seed-xiaochengxu-dazhi',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(200, 1200),
  },
  {
    id: 'zhang-seed-2013-product-worldview',
    title: '互联网产品世界观：人文价值最本质',
    keywords: ['人文价值', '产品世界观', '沟通进化', '简便体验'],
    date: '2013-01-01',
    conversationId: 'zhang-seed-2013-product-worldview',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(240, 1200),
  },
  {
    id: 'zhang-seed-video-channel-future',
    title: '视频号：视频化表达是未来方向',
    keywords: ['视频号', '视频化', '短视频', '人人创作'],
    date: '2021-01-19',
    conversationId: 'zhang-seed-video-channel-future',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(280, 1200),
  },
  {
    id: 'zhang-seed-info-diversity',
    title: '信息多样性：推送决定用户看什么',
    keywords: ['信息多样性', '长尾内容', '推荐算法', '信息茧房'],
    date: '2020-01-01',
    conversationId: 'zhang-seed-info-diversity',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(320, 1200),
  },

  // ── 第三圈（半径 1850）── 深度思想 ─────────────────────────────────────────
  {
    id: 'zhang-seed-shi-ti-yanshen',
    title: '手机是人体的延伸',
    keywords: ['手机延伸', '人体器官', '产品哲学', '麦克卢汉'],
    date: '2012-01-01',
    conversationId: 'zhang-seed-shi-ti-yanshen',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(0, 1850),
  },
  {
    id: 'zhang-seed-product-manager-godlike',
    title: '产品经理和上帝一样：制定规则',
    keywords: ['产品经理', '规则制定', '群体行为', '上帝视角'],
    date: '2012-01-01',
    conversationId: 'zhang-seed-product-manager-godlike',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(24, 1850),
  },
  {
    id: 'zhang-seed-zuizhong-yonghu',
    title: '99%情况下否定新点子',
    keywords: ['需求审查', '否定新点子', '主场景', '需求真伪'],
    date: '2012-01-01',
    conversationId: 'zhang-seed-zuizhong-yonghu',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(48, 1850),
  },
  {
    id: 'zhang-seed-shijian-jiaohu',
    title: '场景化设计：先做结构后做细节',
    keywords: ['场景设计', '结构优先', '主流程', '产品骨架'],
    date: '2012-01-01',
    conversationId: 'zhang-seed-shijian-jiaohu',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(72, 1850),
  },
  {
    id: 'zhang-seed-foxmail-origin',
    title: '从Foxmail到微信：产品人的进化',
    keywords: ['Foxmail', '微信诞生', '产品人成长', '机遇把握'],
    date: '2013-01-01',
    conversationId: 'zhang-seed-foxmail-origin',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(96, 1850),
  },
  {
    id: 'zhang-seed-gongyizhong-open-class-2016',
    title: '2016微信公开课：小程序发布',
    keywords: ['小程序发布', '不需要安装', '随处可用', '应用内应用'],
    date: '2016-01-11',
    conversationId: 'zhang-seed-gongyizhong-open-class-2016',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(120, 1850),
  },
  {
    id: 'zhang-seed-3days-think',
    title: '三天没想出答案，三个月也想不出',
    keywords: ['效率思维', '攻坚思考', '时间质量', '决策速度'],
    date: '2021-01-01',
    conversationId: 'zhang-seed-3days-think',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(144, 1850),
  },
  {
    id: 'zhang-seed-gongzhonghao-ecosystem',
    title: '公众号内容生态：好内容是根本',
    keywords: ['公众号', '内容生态', '洗稿打击', '优质内容'],
    date: '2019-01-09',
    conversationId: 'zhang-seed-gongzhonghao-ecosystem',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(168, 1850),
  },
  {
    id: 'zhang-seed-product-soul',
    title: '产品要有灵魂，不做数字的奴隶',
    keywords: ['产品灵魂', '数字奴隶', '小而美', '初心'],
    date: '2021-01-19',
    conversationId: 'zhang-seed-product-soul',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(192, 1850),
  },
  {
    id: 'zhang-seed-privacy-ethics',
    title: '精准广告与用户隐私的矛盾',
    keywords: ['隐私', '精准广告', '技术伦理', '用户尊重'],
    date: '2020-01-01',
    conversationId: 'zhang-seed-privacy-ethics',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(216, 1850),
  },
  {
    id: 'zhang-seed-because-see-exists',
    title: '因你看见，所以存在',
    keywords: ['因你看见', '存在感', '微信哲学', '7.0版本'],
    date: '2019-01-09',
    conversationId: 'zhang-seed-because-see-exists',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(240, 1850),
  },
  {
    id: 'zhang-seed-xiaoyouxi-creativity',
    title: '小游戏：创意的平台，不以收入为标准',
    keywords: ['小游戏', '创意平台', '原创游戏', '非功利'],
    date: '2019-01-09',
    conversationId: 'zhang-seed-xiaoyouxi-creativity',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(264, 1850),
  },
  {
    id: 'zhang-seed-weixin-anomaly',
    title: '微信是一个"异类"',
    keywords: ['异类', '守住底线', '好产品标准', '坚持风格'],
    date: '2019-01-09',
    conversationId: 'zhang-seed-weixin-anomaly',
    category: '思考世界',
    color: '#8B5CF6',
    nodeType: 'memory',
    ...pos(288, 1850),
  },
  {
    id: 'zhang-seed-problem-complex-wrong',
    title: '解决方案非常复杂，说明问题错了',
    keywords: ['问题重构', '复杂度', '解决方案', '奥卡姆剃刀'],
    date: '2012-01-01',
    conversationId: 'zhang-seed-problem-complex-wrong',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(312, 1850),
  },
  {
    id: 'zhang-seed-aesthetic-capability',
    title: '产品美感不会超过产品经理的审美能力',
    keywords: ['审美能力', '产品气质', '视觉品味', '产品经理素养'],
    date: '2012-01-01',
    conversationId: 'zhang-seed-aesthetic-capability',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(336, 1850),
  },
  {
    id: 'zhang-seed-2017-miniprogram-launch',
    title: '小程序正式发布：无需下载，用完即走',
    keywords: ['小程序发布', '2017年1月', '用完即走', '应用生态'],
    date: '2017-01-09',
    conversationId: 'zhang-seed-2017-miniprogram-launch',
    category: '工作事业',
    color: '#3B82F6',
    nodeType: 'memory',
    ...pos(355, 1850),
  },
]

export const ZHANG_SEED_EDGES: Edge[] = [
  // 核心：用完即走哲学
  {
    id: 'zhang-edge-1',
    source: 'zhang-seed-yong-wan-ji-zou',
    target: 'zhang-seed-77-product-principles',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.95,
  },
  {
    id: 'zhang-edge-2',
    source: 'zhang-seed-yong-wan-ji-zou',
    target: 'zhang-seed-good-product-standards',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.92,
  },
  {
    id: 'zhang-edge-3',
    source: 'zhang-seed-yong-wan-ji-zou',
    target: 'zhang-seed-xiaochengxu-dazhi',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.9,
  },
  {
    id: 'zhang-edge-4',
    source: 'zhang-seed-jian-dan-meigangguan',
    target: 'zhang-seed-77-product-principles',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.88,
  },
  {
    id: 'zhang-edge-5',
    source: 'zhang-seed-jian-dan-meigangguan',
    target: 'zhang-seed-problem-complex-wrong',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.85,
  },
  {
    id: 'zhang-edge-6',
    source: 'zhang-seed-good-product-standards',
    target: 'zhang-seed-aesthetic-capability',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.82,
  },
  {
    id: 'zhang-edge-7',
    source: 'zhang-seed-2019-weixin-open-class',
    target: 'zhang-seed-peopleset-guanxi',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.93,
  },
  {
    id: 'zhang-edge-8',
    source: 'zhang-seed-2019-weixin-open-class',
    target: 'zhang-seed-xiaochengxu-dazhi',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.88,
  },
  {
    id: 'zhang-edge-9',
    source: 'zhang-seed-2019-weixin-open-class',
    target: 'zhang-seed-because-see-exists',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.9,
  },
  {
    id: 'zhang-edge-10',
    source: 'zhang-seed-2021-weixin-open-class',
    target: 'zhang-seed-video-channel-future',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.95,
  },
  {
    id: 'zhang-edge-11',
    source: 'zhang-seed-2021-weixin-open-class',
    target: 'zhang-seed-product-soul',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.88,
  },
  {
    id: 'zhang-edge-12',
    source: 'zhang-seed-2021-ten-years-methodology',
    target: 'zhang-seed-3days-think',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.79,
  },
  {
    id: 'zhang-edge-13',
    source: 'zhang-seed-xiaochengxu-dazhi',
    target: 'zhang-seed-2017-miniprogram-launch',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.91,
  },
  {
    id: 'zhang-edge-14',
    source: 'zhang-seed-xiaochengxu-dazhi',
    target: 'zhang-seed-gongyizhong-open-class-2016',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.89,
  },
  {
    id: 'zhang-edge-15',
    source: 'zhang-seed-shi-ti-yanshen',
    target: 'zhang-seed-renxing-vs-jishu',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.83,
  },
  {
    id: 'zhang-edge-16',
    source: 'zhang-seed-product-manager-godlike',
    target: 'zhang-seed-shejin-yiyao',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.81,
  },
  {
    id: 'zhang-edge-17',
    source: 'zhang-seed-2020-weixin-open-class',
    target: 'zhang-seed-privacy-ethics',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.87,
  },
  {
    id: 'zhang-edge-18',
    source: 'zhang-seed-2020-weixin-open-class',
    target: 'zhang-seed-info-diversity',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.84,
  },
  {
    id: 'zhang-edge-19',
    source: 'zhang-seed-2018-jump-game',
    target: 'zhang-seed-xiaoyouxi-creativity',
    edgeType: 'logical',
    relation: '启发了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.77,
  },
  {
    id: 'zhang-edge-20',
    source: 'zhang-seed-77-product-principles',
    target: 'zhang-seed-zuizhong-yonghu',
    edgeType: 'logical',
    relation: '深化了',
    createdAt: '2024-01-01T00:00:00.000Z',
    confidence: 0.86,
  },
]
